### ISSUE TITLE
SD problems with another SPI BUS (different pins)

### ISSUE THREAD

**Issue by immortal-sniper1** [khoih-prog/RP2040_SD#9] opened 2022-10-31 15:39 UTC
I am trying to use this library on:
rpi pico
using Arduino IDE 
with the latest libraries as of now
I am trying to use some other pins then those on the sketch but they should also be fine since i checked the pin out.
I also tested all relevant pins with a blink sketch and they all work well. Additionally i also tested the SD card and breakout on an Uno and they work fine.
Note: SD is formatted as FAT32 and is 2G. Also I tried the dataloger sketch and i have the same problems.

Serial output: 
----------------------------------------------------------------
* is a card inserted?
* is your wiring correct?
* did you change the chipSelect pin to match your shield or module?
Starting SD Card CardInfo on RASPBERRY_PI_PICO
RP2040_SD v1.0.1
Initializing SD card with SS = 17
SCK = 18
MOSI = 19
MISO = 16
initialization failed. Things to check:
* is a card inserted?
* is your wiring correct?
* did you change the chipSelect pin to match your shield or module?
-----------------------------------------------------------------------------------------------------

`my` code:
https://github.com/immortal-sniper1/RP2040_basic_board/tree/main/SW/CardInfo_alt_lib

**Comment by immortal-sniper1** [comment] 2022-10-31 15:40
NOTE: I also tried with PlatformIO and i also had the same problems there

**Comment by khoih-prog** [comment] 2022-10-31 18:30
HI @immortal-sniper1 

> This library was created as an effort to use SD Card while the `arduino-pico` core still has issue [**SD card FILE_WRITE issue** #214](https://github.com/earlephilhower/arduino-pico/issues/214), which has been fixed from core v1.8.6.
> 
> It's better to use the built-in [SD library](https://github.com/earlephilhower/arduino-pico/tree/master/libraries/SD) for [**Earle Philhower's arduino-pico core v1.8.6+**](https://github.com/earlephilhower/arduino-pico). 
> 
> But if you need to write codes to be used in both [**Arduino-mbed RP2040** core](https://github.com/arduino/ArduinoCore-mbed) and [**Earle Philhower's arduino-pico core**](https://github.com/earlephilhower/arduino-pico) without having to modify the code, you can have the option to use this library.

I suggest you try the `arduino-pico` [**SD** library](https://github.com/earlephilhower/arduino-pico/tree/master/libraries/SD).

Also be sure you understand what you're doing, and **use / init SPI bus correctly**, as you can't just use any pin as you'd like.

Unless you prove the issue is a bug of this library, I'm closing it now.

Good Luck,

**Closed by khoih-prog** 2022-10-31 18:30 UTC
